# Generated by Django 5.0.6 on 2024-06-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Клиента", "verbose_name_plural": "Клиенты"},
        ),
    ]
